server:
  port: 8767

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lei911gang/springcloud-config
          searchPaths: config-file
          username: lei911gang
          password: ******
      label: master
  rabbitmq:
      host: localhost
      port: 5672
      username: rabbitadmin
      password: 123456

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.application.name}:${server.port}
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/

management:
  security:
    enabled: false #是否开启actuator安全认证

#使用本地属性文件
#spring.profiles.active: native

#属性文件地址，只要指定文件夹的路径
#spring.cloud.config.server.native.searchLocations: classpath:/
